# https://stackoverflow.com/questions/28904247/zuul-timing-out-in-long-ish-requests

server:
    port: 8080

spring:
    application:
        name: gateway

ribbon:
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true


eureka:
    enabled: true

hystrix:
    command:
        stock:
            execution:
                isolation:
                    strategy: THREAD
                    thread:
                        timeoutInMilliseconds: 2000
        ecommerce:
            execution:
                isolation:
                    strategy: THREAD
                    thread:
                        timeoutInMilliseconds: 2000

zuul:
    host:
        max-total-connections: 60000
        max-per-route-connections: 60000
    semaphore:
        max-semaphores: 500
    ignoredServices: "*"
    routes:
        ecommerce: 
            path: /ecommerce/**
            serviceId: ecommerce

        stock: 
            path: /stock/**
            serviceId: stock